const fs = require('fs');
(async () => {
    let rawGames = await fs.readFileSync('gamelist.txt');
    rawGames = rawGames.toString().split('\n');

    let games = [];
    function checkEntry(entry) {
        return entry != '' && (entry.startsWith('||') && entry.endsWith('^')) && !entry.includes('/');
    }
    for (let i = 0; i < rawGames.length; i++) {
        let entry = rawGames[i].toString();
        if (checkEntry(entry)) {
            entry = entry.split('||')[1];
            entry = entry.split('^')[0];
            // console.log(entry);
            games.push(entry);
        }
    }

    let gamesHosts = [];
    for (let i = 0; i < games.length; i++) {
        let entry = `0.0.0.0 ${games[i].toString()}`;
        gamesHosts.push(entry);
    }

    let finalHosts = [
        `# Growing list of domains related to games`,
        `# From RealStr1ke @ github`,
        '# This file is automatically generated by the gamelist.js script.',
        '# Do not edit this file directly.',
        '',
        gamesHosts.join('\n')
    ];
    await fs.writeFileSync('gamelist.hosts', finalHosts.join('\n'));
})();
